import Head from 'next/head'
import {BsFillMoonStarsFill, BsFillSunFill} from 'react-icons/bs'
import {AiFillLinkedin, AiOutlineGithub} from 'react-icons/ai'
import Image from 'next/image'
import afigueres from '../public/avatar.jpg'
import palmTree from '../public/palm-tree.png'
import dumbbell from '../public/dumbbell.png'
import code from '../public/code.png'
import web2 from '../public/web2.png'
import {useState} from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  const downloadPDF = () => {
    // using Java Script method to get PDF file
    fetch('CV.pdf').then(response => {
        response.blob().then(blob => {
            // Creating new object of PDF file
            const fileURL = window.URL.createObjectURL(blob);
            // Setting various property values
            let alink = document.createElement('a');
            alink.href = fileURL;
            alink.download = 'AdriaFigueresCV.pdf';
            alink.click();
        })
    })
  }
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Adria Figueres Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-slate-200'>Adria Figueres</h1>
            <ul className='flex items-center'>
              <li>
                {darkMode 
                  ? <BsFillSunFill onClick={() => setDarkMode(!darkMode)} className='text-white cursor-pointer' />
                  : <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer' />
                }
              </li>
              <li>
                <button className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' onClick={downloadPDF}>
                    Download CV
                </button>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 pb-2'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Adria Figueres</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-slate-200'>Software engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-slate-200 text-justify'>
              Senior PHP developer specialized in back-end developments, with a strong focus on quality, 
              improving the processes and practices of the teams where I am involved. Having more than 5 
              years of experience, my goal is not just delivering working software but consolidating solid 
              architectures and optimizing the maintainability of the final result
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://www.linkedin.com/in/adria-figueres-garcia-814425156/" target={'blank'}><AiFillLinkedin /></a>
            <a href="https://github.com/adryyy10" target={'blank'}><AiOutlineGithub /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 my-20 overflow-hidden md:h-96 md:w-96'>
            <Image alt='adria' src={afigueres} />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-slate-200'>Soft skills</h3>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white basis-1/3 flex-1'>
              <Image alt='code' src={palmTree} width={100} height={100} className="inline" />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Resilience
              </h3>
              <p className='py-2'>
                Resilience is the ability to <span className=' font-bold text-teal-500'>adapt</span> to difficult situations. 
                Being a developer, it often happens that we find ourselves facing problems and complexities in the approach 
                of our code, the only option is to <span className=' font-bold text-teal-500'>never give up </span>.
              </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white basis-1/3 flex-1'>
              <Image alt='code' src={dumbbell} width={100} height={100} className="inline" />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Discipline
              </h3>
              <p className='py-2'>
                Hard work pays off. As a developer (and in life in general) it takes discipline in order to keep <span className='font-bold text-teal-500'>growing </span> 
                as a professional. The world in constant evolution makes you have to always be aware of new changes and things to <span className='font-bold text-teal-500'>learn</span>.
              </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white basis-1/3 flex-1'>
              <Image alt='code' src={code} width={100} height={100} className="inline" />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Empathy
              </h3>
              <p className='py-2'>
                The hability to <span className='font-bold text-teal-500'>understand </span> and share the feelings of another. We are constantly working with people and it is <span className='font-bold text-teal-500'>essential </span> to listen and understand your teammates to be a good professional in the IT world.
              </p>

            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-slate-200'>Portfolio</h3>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image alt='Project' src={web2} className="rounded-lg object-cover" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image alt='Project' src={web2} className="rounded-lg object-cover" />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
